# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/*.coverage'
    reportDirectory: $(Build.SourcesDirectory)\results
    codecoverageTool: cobertura

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '**/*.coverage'
    ArtifactName: 'coverage'
    publishLocation: 'Container'